[features]
seeds = false
[programs.localnet]
mysolanaapp = "9cSskb3Cq4WEw2GMdZxDBVDW4kbK7ipsqi1KbpQLsFcV"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/otp/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
